---
name: aedit
base: core22
version: '1.1.71'
icon: meta/gui/icon.png
license: GPL-3.0
contact: rhubarb-geek-nz@users.sourceforge.net
website: https://github.com/rhubarb-geek-nz/aedit
source-code: https://github.com/rhubarb-geek-nz/aedit-snapcraft.git
summary: Text Editor based on Intel ISIS-II aedit
description: |
  Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter.
  This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.
  
  Features
  
  * Written in ANSI C
  * Highly portable
  * No curses or other libraries required
  * Single source file
  * Block highlighting.
  * Clipboard.
  * Window resizing.
  * Uses temporary file to deal with large files.
  * Works over SSH, including on Windows

grade: stable
confinement: strict

parts:
  aedit:
    source: https://github.com/rhubarb-geek-nz/aedit/archive/refs/tags/1.1.71.tar.gz
    plugin: make
    make-parameters: [CFLAGS+="-Wall -Werror", aedit]

apps:
  aedit:
    command: usr/bin/aedit
    plugs: [home, network, network-bind, removable-media]
