---
name: aedit
base: core18
version: '1.1.82'
icon: meta/gui/icon.png
summary: Text Editor based on Intel ISIS-II aedit
description: |
  Text editor based on interface from Intel ISIS-II aedit, which in turn was based on its big brother alter.
  This was originally written in the mid 80s on QNX running on an 8088, with a CBM-64 acting as the console.

grade: stable
confinement: strict

parts:
  aedit:
    source: https://github.com/rhubarb-geek-nz/aedit/archive/refs/tags/1.1.82.tar.gz
    plugin: make
    make-parameters: [CFLAGS+=-pedantic -Wall -Werror, aedit]

apps:
  aedit:
    command: usr/bin/aedit
    plugs: [home, network, network-bind, removable-media]
